[package]
name = "polars-corpus"
version = "0.1.0"
edition = "2024"

[lib]
name = "polars_corpus"
crate-type= ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", default-features = false, features = ["extension-module", "abi3-py39", "nightly"] }
polars = { version = "0.49", default-features = false }
pyo3-polars = { version = "0.22", default-features = false, features = ["derive"] }
itertools = "0.14"
polars-arrow = { version = "0.49", default-features = false }
