site_name: polars-corpus

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
            docstring_style: numpy
            show_root_heading: true
            show_root_full_path: false
            show_signature: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            separate_signature: true
            docstring_section_style: list

  - mkdocs-jupyter:
      execute: true
      include_requirejs: true
      custom_mathjax_url: "https://cdn.jsdelivr.net/npm/mathjax@4/tex-svg.js"

nav:
  - Home: index.md
#  - User Guide:
#      - Getting started: guide/getting-started.ipynb
#      - Working with corpora: guide/corpora.ipynb
  - Examples:
      - Keyword Analysis: notebooks/keywords.ipynb
      - Dispersion: notebooks/dispersion.ipynb
  - Reference:
#      - Corpus: api/corpus.md
      - API: api.md