[build-system]
requires = ["maturin>=1.0,<2.0", "polars>=1.33"]
build-backend = "maturin"

[project]
name = "polars-corpus"
version = "0.2.0-pre"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Rust",
    "Programming Language :: Python",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Text Processing",
    "Topic :: Text Processing :: General",
    "Topic :: Text Processing :: Linguistic",
    "Typing :: Typed",
]
authors = [
    {name = "Rob Malouf", email="rmalouf@sdsu.edu"}
]
description = "Text processing plugins for polars"
readme = "README.md"
license = "MIT"
dependencies = [
    "polars>=1.34",
    "lark>=1.2",
    "nltk>=3.9",
    "ipywidgets>=8.1"
]

[tool.pyrefly.errors]
bad-override-mutable-attribute = "ignore"

#[project.urls]
#Homepage = "https://example.com"
#Documentation = "https://readthedocs.org"
#Repository = "https://github.com/me/spam.git"
#Issues = "https://github.com/me/spam/issues"
#Changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[tool.uv]
python-preference = "only-managed"

[tool.mypy]
ignore_missing_imports = true
strict = true

[[tool.mypy.overrides]]
module = "polars_corpus._internal"
ignore_missing_imports = true

[tool.maturin]
module-name = "polars_corpus._internal"
python-source = "python"

[tool.pyrefly]
ignore-missing-imports = [
    "polars_corpus._internal",
    "*",
]

[dependency-groups]
dev = [
 "jupyterlab>=4.4.0",
 "maturin>=1.8.3",
 "notebook>=7.4.0",
 "pip>=25.0.1",
 "pyrefly>=0.62",
 "pytest>=8.3.5",
 "quartodoc>=0.7",
 "griffe<2.0",
]
