[build-system]
requires = ["maturin>=1.0,<2.0", "polars>=1.25"]
build-backend = "maturin"

[project]
name = "polars-corpus"
version = "0.1.0"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Rust",
    "Programming Language :: Python",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Text Processing",
    "Topic :: Text Processing :: General",
    "Topic :: Text Processing :: Linguistic",
    "Typing :: Typed",
]
authors = [
    {name = "Rob Malouf", email="rmalouf@sdsu.edu"}
]
description = "Text processing plugins for polars"
readme = "README.md"
license = "MIT"
#dependencies = [s
 ##"nltk>=3.9.1",
# "polars>=1.27.1",
 #"seaborn>=0.13.2",s
 #"spacy[apple]==3.8.*",
 #"en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl",
 #"en-core-web-trf @ https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl",
#]

#[project.urls]
#Homepage = "https://example.com"
#Documentation = "https://readthedocs.org"
#Repository = "https://github.com/me/spam.git"
#Issues = "https://github.com/me/spam/issues"
#Changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[tool.uv]
python-preference = "only-managed"

[tool.mypy]
ignore_missing_imports = true
strict = true

[[tool.mypy.overrides]]
module = "polars_corpus._internal"
ignore_missing_imports = true

[tool.maturin]
module-name = "polars_corpus._internal"
python-source = "python"


# [dependency-groups]
# dev = [
#     "jupyterlab>=4.4.0",
#     "maturin>=1.8.3",
#     "mypy>=1.15.0",
#     "notebook>=7.4.0",
#     "pip>=25.0.1",
#     "pytest>=8.3.5",
# ]
