from __future__ import annotations

import polars as pl

def py_concordance(
    df: pl.DataFrame,
    matches: list[Match],
    chunk_tag: pl.Series,
) -> pl.DataFrame: ...
def py_kwic(
    df: pl.DataFrame,
    matches: list[Match],
    left_window: int,
    right_window: int,
) -> pl.DataFrame: ...
def spans_to_chunks(spans: list[Span], n: int) -> pl.Series: ...

class Span:
    start: int
    end: int
    def __init__(self, start: int, end: int) -> None: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, index: int) -> int: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class Match:
    span: Span
    bindings: dict[str, Span]
    def __init__(self, span: Span, bindings: dict[str, Span]) -> None: ...

class Opcode:
    @staticmethod
    def Token(mask: bytes) -> Opcode: ...
    @staticmethod
    def Skip() -> Opcode: ...
    @staticmethod
    def Jump(offset: int) -> Opcode: ...
    @staticmethod
    def Split(offset1: int, offset2: int) -> Opcode: ...
    @staticmethod
    def Match() -> Opcode: ...
    @staticmethod
    def PushVar() -> Opcode: ...
    @staticmethod
    def PopVar() -> Opcode: ...
    @staticmethod
    def BindVar(name: str) -> Opcode: ...
    @staticmethod
    def UnBindVar() -> Opcode: ...
    @staticmethod
    def Fail() -> Opcode: ...

class OpcodeMatcher:
    def __init__(self, opcodes: list[Opcode], masks: list[pl.Series]) -> None: ...
    def matchall(self) -> list[Match] | None: ...
